name: push-build-release
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }} 
on: 

  push:
    tags:
      - 'v*'
  pull_request:
    branches: [develop]
jobs:
  build_test_package:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest] 

    uses: EddyTheCo/Common/.github/workflows/build-test-install.yml@v0.1.2
    permissions:
      contents: write
    with:
      os: ${{ matrix.os }}
      qtModules: 'qtshadertools'
      qtVersion: '6.6.0'  
      test: false  
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build_test_package
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
          
      - uses: actions/checkout@v4
    
      - uses: actions/download-artifact@v4
        with:
           path: artifacts
      - name: Releases 
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*/*       
